export const PostData = [
    
    {
        icon:icon.svg,
        nickname:"みつなが",
        code:2341-7899-7384,
        title:"ゆる〜くブキ練習！",
        text:"今まで使ったことのないブキを練習したいです！どんなブキ使ってもいいよって人お願いします！",
        mode:asari,
        xp:1600,
        erea:gonnzui.jpg,
    }
    ,
    {
        id:"",
        icon: icon.svg ,
        nickname : "和弘",
        code : 3754-8546-4857,
        title : "アサリ練習の相手募集",
        text : "ガチアサリが死ぬほど苦手です。克服したいのでガチアサリ練習に付き合ってくださる方を募集してます。",
        mode:asari,
        xp:1600,
        erea : masaba.jpg,
    }
    ,
    {
        id:"",
        icon: icon.svg ,
        nickname : "リョウ",
        code : 5703-9247-3349,
        title : "おしゃべり会",
        text : "スプラで遊んでくれる友達がいないので友達募集中です。おしゃべりしながらまったり遊びたいです。",
        mode:asari,
        xp:1600,
        erea : tyouzame.jpg,
    }
    ,
    {
        id:"",
        icon: icon.svg ,
        nickname : "may",
        code : 4324-4595-3467,
        title : "スプラ女子会",
        text : "深夜に一緒に遊んでくれる人募集中！女子のスプラ仲間が欲しいです！",
        mode:asari,
        xp:1600,
        erea : yunohana.jpg,
    }
    ,
    {
        id:"",
        icon: icon.svg ,
        nickname : "ライト",
        code : 4637-6847-3945,
        title : "まったり深夜スプラ",
        text : "平日深夜の夜更かしに一緒にスプラしてくれる人探してます。",
        mode:asari,
        xp:1600,
        erea : yunohana.jpg,
    }
    ,
    {
        id:"",
        icon: icon.svg ,
        nickname : "つくし",
        code : 3472-8457-4573,
        title : "カスタムマッチ募集",
        text : "楽しく遊んでくださる方〜いませんか〜？",
        mode:asari,
        xp:1600,
        erea : namerou.jpg,
    }
    ,
    {
        id:"",
        icon: icon.svg ,
        nickname : "ある",
        code : 3748-3475-3459,
        title : "ホクサイ祭り開催",
        text : "ホクサイ縛りでわちゃわちゃしたいです！",
        mode:asari,
        xp:1600,
        erea : mategai.jpg,
    }
    ,
    {
        id:"",
        icon: icon.svg ,
        nickname : "七兵衛",
        code : 3645-7546-3495,
        title : "配信者限定カスタム",
        text : "スプラの配信者集まれ〜〜",
        mode:asari,
        xp:1600,
        erea : tyouzame.jpg,
    }
    ,
    {
        id:"",
        icon: icon.svg ,
        nickname : "りょ〜ゆ〜",
        code : 3957-4853-2945,
        title : "フェス前練習！！！",
        text : "フェスで〇〇陣営の方、一緒に遊びませんか？",
        mode:asari,
        xp:1600,
        erea : masaba.jpg,
    }
    ,
    {
        id:"",
        icon: icon.svg ,
        nickname : "yuki",
        code : 9348-4573-4592,
        title : "初心者、カスタムマッチ練習",
        text : "ガチマッチの立ち回りを練習したいので、初心者でもいいよ〜って方お願いします",
        mode:asari,
        xp:1600,
        erea : namerou.jpg,
    }
    ,
    {
        id:"",
        icon: icon.svg ,
        nickname : "夏葉",
        code : 7324-3958-3475,
        title : "リア充爆破カスタム",
        text : "クリスマスにボッチなのが辛いので誰か慰めてください",
        mode:asari,
        xp:1600,
        erea : namerou.jpg,
    },
    
]